baseurl: https://gracious-curran-ee29fc.netlify.app/
languageCode: en-us
title: Ankit's Blog
theme: hugo-lithium
googleAnalytics: 'G-59DDLZ8LQE'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: true
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: about/
    - name: GitHub
      url: https://github.com/ak10net
    - name: Twitter
      url: https://twitter.com/akionet5
    - name: Linkedin
      url: https://www.linkedin.com/in/ankit-d-689704157/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
